### ISSUE TITLE
Quality control check

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/wheelerutoaztecan#1]
please!

(I did try to get the add_* functions working without iteration, but couldn't figure it out). 

Data is theoretically all IPA, so should be pretty clean too.

**Comment by LinguList** [comment]
you could make a first lingpy orthoprofile, to see how it works:

```
lingpy profile -i cldf/cldf-metadata.json -o etc/orthography.tsv --cldf --clts --context --column=form
```

**Comment by xrotwang** [comment]
@LinguList will do while quality controling

**Comment by SimonGreenhill** [comment]
most of this code comes from the old lexibank, I've just brushed it off a bit. While going though issues I realised we had already added this dataset.

**Comment by LinguList** [comment]
Yes, many things can be simplified now, I guess, specifically concept handling. We can leave this open until filled.

**Comment by SimonGreenhill** [comment]
Cool -- [private use unicode characters](https://github.com/lexibank/wheelerutoaztecan/blob/master/etc/orthography.tsv#L61) :/
