### ISSUE TITLE
Can we fix the profile?

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/wheelerutoaztecan#4]
Only a few outstanding issues.

**Comment by LinguList** [comment]
yes, I assume, but it will include some digging in Uto-Aztekan phonology, but we should have the ambition to fix it.

**Comment by tresoldi** [comment]
Yes, look like we could get 100% rather quickly.

**Comment by tresoldi** [comment]
Sorry @SimonGreenhill , I need writing permission here as well. Good news is that the profile is finished, 100% (with some doubts).

**Comment by SimonGreenhill** [comment]
try now?

**Comment by SimonGreenhill** [comment]
And wonderful work BTW, thanks :)

**Comment by tresoldi** [comment]
Working, thanks!
